"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

from pathlib import Path
from app.env import get_env

env = get_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l2a^)4qqwfs#cj!q6jnfrh=0%zcy367s=2ff4=now@!yxqp@_f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.django_debug_mode

# DjangoのALLOWED_HOSTS | Qiita: https://qiita.com/kkk777/items/b9452738bc5d3bb35542
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Pollsアプリケーション: polls/app.py:PollsConfig
    'polls.apps.PollsConfig',
    # 管理サイト: https://docs.djangoproject.com/ja/5.0/ref/contrib/admin/#module-django.contrib.admin
    'django.contrib.admin',
    # 認証システム: https://docs.djangoproject.com/ja/5.0/topics/auth/#module-django.contrib.auth
    'django.contrib.auth',
    # コンテンツタイプフレームワーク: https://docs.djangoproject.com/ja/5.0/ref/contrib/contenttypes/#module-django.contrib.contenttypes
    'django.contrib.contenttypes',
    # セッションフレームワーク: https://docs.djangoproject.com/ja/5.0/topics/http/sessions/#module-django.contrib.sessions
    'django.contrib.sessions',
    # メッセージフレームワーク: https://docs.djangoproject.com/ja/5.0/ref/contrib/messages/#module-django.contrib.messages
    'django.contrib.messages',
    # 静的ファイル管理フレームワーク: https://docs.djangoproject.com/ja/5.0/ref/contrib/staticfiles/#module-django.contrib.staticfiles
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
db_secret = env.get_db_secret()
DATABASES = {
    "default": {
        # https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-DATABASE-ENGINE
        "ENGINE": "django.db.backends.mysql",
        "NAME": env.db_name,
        "USER": db_secret.db_user,
        "PASSWORD": db_secret.db_password,
        "HOST": db_secret.db_host,
        "PORT": db_secret.db_port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# https://docs.djangoproject.com/ja/5.0/ref/settings/#std-setting-TIME_ZONE
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# 静的ファイルのURLの接頭辞
STATIC_URL = 'static/'

# 静的ファイルのディレクトリ
STATIC_ROOT = os.path.join(BASE_DIR, "static_dst")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
